version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: ludo-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ludopassword123
      MONGO_INITDB_DATABASE: multiplayer-ludo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - ludo-network
    command: mongod --bind_ip_all

  # Remove MongoDB replica set setup for now
  # mongo-setup:
  #   image: mongo:7.0
  #   container_name: ludo-mongo-setup
  #   depends_on:
  #     - mongodb
  #   restart: "no"
  #   networks:
  #     - ludo-network

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ludo-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8080
      CONNECTION_URI: mongodb://admin:ludopassword123@mongodb:27017/multiplayer-ludo?authSource=admin
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - ludo-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ludo-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ludo-network
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000

volumes:
  mongodb_data:
    driver: local

networks:
  ludo-network:
    driver: bridge