services:
  # Backend API Service
  - type: web
    name: multiplayer-ludo-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CONNECTION_URI
        fromDatabase:
          name: multiplayer-ludo-db
          property: connectionString
    healthCheckPath: /

databases:
  # PostgreSQL Database (free tier)
  - name: multiplayer-ludo-db
    plan: free